[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rt = {path = "../rt",features = ["tokio"]}
dict_gen = {path = "../dict_gen"}
radius_core = { package="core", path = "../core" }
anyhow = "1.0"
async-trait = "0.1.88"
tokio = { version = "1",  features = ["full"] }
[features]
tokio = ["rt/tokio"]

